;; refresh_lists.cljs — fetch + parse + normalize + write watchlist source
;; data. nbb only (this repo-wide toolchain rule: no bb/babashka scripts).
;;
;; Usage (from this repo's root, classpath includes src/):
;;   nbb -cp src scripts/refresh_lists.cljs [--out DIR] [--sources ofac-sdn,un-consolidated]
;;
;; Writes <DIR>/<source>.entities.edn (a vector of watchlist.model entity
;; maps) and <DIR>/<source>.manifest.edn (a watchlist.model list-manifest
;; map: fetched-at/source-published-at/entity-count/sha256) per source --
;; the shape watchlist.adapters.edn-index reads. Default DIR is
;; resources/watchlist/lists (relative to cwd).
;;
;; :eu-consolidated is deliberately absent from `sources` below -- see
;; watchlist.adapters.eu-consolidated's module doc (the EU's machine-
;; readable source requires a registered access token this script does
;; not have).

(ns refresh-lists
  (:require ["node:crypto" :as crypto]
            ["node:fs" :as fs]
            ["node:path" :as path]
            [watchlist.adapters.ofac-sdn :as ofac]
            [watchlist.adapters.un-consolidated :as un]))

(def sources
  {:ofac-sdn {:url "https://www.treasury.gov/ofac/downloads/sdn.xml" :parse ofac/parse}
   :un-consolidated {:url "https://scsanctions.un.org/resources/xml/en/consolidated.xml" :parse un/parse}})

(defn- sha256 [s] (-> (crypto/createHash "sha256") (.update s "utf8") (.digest "hex")))

(defn- fetch-text [url]
  (-> (js/fetch url)
      (.then (fn [res]
               (if (.-ok res)
                 (.text res)
                 (throw (js/Error. (str "fetch failed: " url " -> HTTP " (.-status res)))))))))

(defn- write-source! [out-dir source-key parsed raw-hash fetched-at]
  (let [entities-path (path/join out-dir (str (name source-key) ".entities.edn"))
        manifest-path (path/join out-dir (str (name source-key) ".manifest.edn"))
        manifest {:manifest/source source-key
                  :manifest/fetched-at fetched-at
                  :manifest/source-published-at (:source-published-at parsed)
                  :manifest/entity-count (:entity-count parsed)
                  :manifest/sha256 raw-hash}]
    (fs/mkdirSync out-dir #js {:recursive true})
    (fs/writeFileSync entities-path
                       (str ";; GENERATED by scripts/refresh_lists.cljs -- do not hand-edit.\n"
                            (pr-str (:entities parsed)) "\n"))
    (fs/writeFileSync manifest-path
                       (str ";; GENERATED by scripts/refresh_lists.cljs -- do not hand-edit.\n"
                            (pr-str manifest) "\n"))
    manifest))

(defn refresh-one!
  "Fetch, hash, parse, and write one source. Returns a promise of the
   written manifest. Errors propagate (a failed fetch/parse leaves the
   PREVIOUS entities/manifest files untouched -- never partially overwrite
   good data with a failed refresh's half-result)."
  [out-dir source-key]
  (let [{:keys [url parse]} (get sources source-key)]
    (when-not url (throw (ex-info (str "refresh-lists: unknown source " source-key) {:source source-key})))
    (-> (fetch-text url)
        (.then (fn [raw]
                 (let [hash (sha256 raw)
                       parsed (parse raw)
                       fetched-at (js/Date.now)
                       manifest (write-source! out-dir source-key parsed hash fetched-at)]
                   (println (str (name source-key) ": " (:entity-count parsed) " entities"
                                  ", published " (:source-published-at parsed)
                                  ", sha256 " hash))
                   manifest))))))

(defn- parse-args [argv]
  (loop [args (seq argv) out {:out "resources/watchlist/lists" :sources (keys sources)}]
    (if-not args
      out
      (let [[flag value & more] args]
        (case flag
          "--out" (recur more (assoc out :out value))
          "--sources" (recur more (assoc out :sources (map keyword (clojure.string/split value #","))))
          (recur (rest args) out))))))

(defn -main [& argv]
  (let [{:keys [out sources]} (parse-args argv)]
    (-> (js/Promise.allSettled (map #(refresh-one! out %) sources))
        (.then (fn [results]
                 (let [failures (filter #(= "rejected" (.-status %)) results)]
                   (doseq [f failures] (println "REFRESH FAILED:" (.-reason f)))
                   (when (seq failures)
                     (println (str (count failures) "/" (count results) " source(s) failed -- "
                                    "previous data for those sources, if any, is untouched."))
                     #?(:cljs (js/process.exit 1)))))))))

(apply -main *command-line-args*)
